# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=b'Cardiff', max_length=100, verbose_name='\u57ce\u5e02')),
                ('date', models.CharField(max_length=10, verbose_name='\u65e5\u671f')),
                ('time', models.CharField(max_length=10, verbose_name='\u65f6\u95f4')),
                ('temp', models.FloatField(verbose_name='\u6e29\u5ea6')),
                ('dew_point', models.FloatField(verbose_name='\u9732\u70b9')),
                ('humidity', models.FloatField(verbose_name='\u6e7f\u5ea6')),
                ('pressure', models.IntegerField(verbose_name='\u6c14\u538b')),
                ('visibility', models.FloatField(verbose_name='\u53ef\u89c1\u5ea6')),
                ('wind_dir', models.CharField(max_length=30, verbose_name='\u98ce\u5411')),
                ('wind_speed', models.FloatField(verbose_name='\u98ce\u901f\u5ea6')),
                ('conditions', models.CharField(max_length=30, verbose_name='\u5929\u6c14\u60c5\u51b5')),
            ],
            options={
                'db_table': 'Weather',
                'verbose_name': '\u5929\u6c14\u6570\u636e',
                'verbose_name_plural': '\u5929\u6c14\u6570\u636e',
            },
        ),
        migrations.CreateModel(
            name='WeatherDayAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=b'Cardiff', max_length=100, verbose_name='\u57ce\u5e02')),
                ('date', models.CharField(max_length=10, verbose_name='\u65e5\u671f')),
                ('temp', models.FloatField(verbose_name='\u6e29\u5ea6')),
                ('dew_point', models.FloatField(verbose_name='\u9732\u70b9')),
                ('humidity', models.FloatField(verbose_name='\u6e7f\u5ea6')),
                ('pressure', models.IntegerField(verbose_name='\u6c14\u538b')),
                ('visibility', models.FloatField(verbose_name='\u53ef\u89c1\u5ea6')),
            ],
            options={
                'db_table': 'WeatherDayAverage',
                'verbose_name': '\u5929\u6c14\u65e5\u5747\u6570\u636e',
                'verbose_name_plural': '\u5929\u6c14\u65e5\u5747\u6570\u636e',
            },
        ),
    ]
