# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherDayAverageTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=b'Cardiff', max_length=100, verbose_name='\u57ce\u5e02')),
                ('date', models.CharField(max_length=10, verbose_name='\u65e5\u671f')),
                ('temp', models.FloatField(verbose_name='\u6e29\u5ea6')),
            ],
            options={
                'db_table': 'WeatherDayAverageTemp',
                'verbose_name': '\u6c14\u6e29\u65e5\u5747\u6570\u636e',
                'verbose_name_plural': '\u6c14\u6e29\u65e5\u5747\u6570\u636e',
            },
        ),
    ]
